### ISSUE TITLE
Feature suggestion: Run on files given from terminal, not on files specified in configuration file

### ISSUE THREAD

**Issue by tomascapek** [hchasestevens/bellybutton#16]
While having an option to specify these files using configuration file is cool, in my use case, it is not the best.

I am creating a tool for code quality checks, which uses pylint and mypy and I want to be able to integrate bellybutton to it. Unfortunately bellybutton doesn't allow to specify, on which files it should run using command line. This turns out to be very limiting, because my tool could be launched on specified files only.

I think, it would be better, if user could specify the files using command line, not only using the configuration file.

I am willing to implement this myself, if you don't {want|have time} to do it yourself, if you like it.

**Comment by hchasestevens** [comment]
Hi @tomascapek , thank you for the suggestions, I'm glad to hear you're getting use out of the tool. Regarding this issue and #17 , for your use case, would it be more sensible to refactor the CLI module to make this integration possible outside of a command-line context?

**Comment by tomascapek** [comment]
I think it would be sensible.

**Comment by hchasestevens** [comment]
@tomascapek I have added in branch `issue-16-specify-files-to-lint` a `linting_failures` function, which takes in an iterable of filepaths and parsed rules, as can be seen here: https://github.com/hchasestevens/bellybutton/blob/issue-16-specify-files-to-lint/bellybutton/cli.py#L130 . Please let me know if this adequately fits your use case (including issue #17 ); if so, I will merge it into master and publish a new release.

**Comment by tomascapek** [comment]
Yes, this fits my needs. Will you be also changing the command line interface or I'll have to use it directly from Python? The first option would be nice ^^ Thanks for you time and effort, I really appreciate it!

**Comment by hchasestevens** [comment]
Hi @thomascapek, would you mind explaining a little why? Outside of non-programmatic use cases, I would prefer to keep the CLI as uncluttered as possible.

**Comment by tomascapek** [comment]
Hello @hchasestevens, it's not really necessary. My reasoning was, that pylint has this option and so I thought, that this tool could also have it. For my use case it isn't really necessary, I can easily call this function from Python and be happy. Once again, many thanks to your great job!

**Comment by hchasestevens** [comment]
@tomascapek I understand. I'll keep the suggestion in mind, but for now have released the necessary refactoring in v.0.2.3.
